### ISSUE TITLE
 What is userId and clientUserId ?

### ISSUE THREAD

**Issue by toseefkhilji** [docusign/docusign-objc-client#13]
Hello there,

I have follow the readme.
Create demo account on web portal.
Created integration key.

But what is  **userId && clientUserId** ?
How can I get it?

File : https://github.com/docusign/docusign-objc-client/blob/master/test/SdkTests/SdkTestsTests/DSTestConfig.m.sample 

![screen shot 2018-05-03 at 5 52 33 pm](https://user-images.githubusercontent.com/2367614/39576173-e6bda47e-4efa-11e8-8a1b-4f8b6330f482.png)

I didn't found any thing this in Admin portal.

**Comment by LarryKlugerDS** [comment]
Hi,
`userId` is the guid version of the DocuSign user whom your application will be impersonating. 
See https://www.docusign.com/blog/dsdev-developing-docusign-application-authentication/ and for more info.

`clientUserId` is the id of the signer in your own application. It needs to be unique per signer. Including the clientUserId field in the Envelopers:create call indicates to DocuSign that the recipient will sign view an embedded signing session. See the DevCenter QuickStart for more: developers.docusign.com

For more help with this type of issue, please StackOverflow, with the `docusignapi` tag. 

Thanks,
Larry

**Comment by toseefkhilji** [comment]
@LarryKlugerDS  I can't ask this type of issue/Question on StackOverflow because it is not a specific programming problem.

**Comment by LarryKlugerDS** [comment]
Hi,
Your question would be, "How do I do embedded signing." And then ask about those settings.

Thanks for using DocuSign.

**Comment by toseefkhilji** [comment]
Thanks for the guide.

**Comment by Kapeutini2018** [comment]
it's confusing, I repeat the question ... what is the clientuserid ?

**Comment by miacloudtech** [comment]
I too am looking for the "user_id". I cannot see it in the Admin page nor under my photo in the top right of the screen. Is it the same as the "API Username"?  I have read that the client_id is the same as the integration key. Thank you for your help.  I am trying to (as simply as possible) integrate our CRM (written in VBscript and classic ASP) which dynamically creates documents which need signing, with Docusign.

**Comment by Kapeutini2018** [comment]
I'm not at work, it is on admin but not at the api part, I'll check
tomorrow, I'm at home and will back to you asap


*--=-- *
*KAP*


Le mer. 9 oct. 2019, à 10 h 20, miacloudtech <notifications@github.com> a
écrit :

**Comment by jporpan24** [comment]
ssaADA
