### ISSUE TITLE
Unnecessarily return value in Methods

### ISSUE THREAD

**Issue by toseefkhilji** [docusign/docusign-objc-client#15]
Hi,

There are Unnecessarily return values in API class (i.e DSAuthenticationApi, DSEnvelopesApi, DSBillingApi, DSFoldersApi, etc.) Methods.
Because there is already completionHandlers.

For example:

```
-(NSNumber*) listSocialLoginsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 completionHandler: (void (^)(DSUserSocialIdResult* output, NSError* error)) handler;

-(NSNumber*) revokeOAuthTokenWithCompletionHandler: (void (^)(NSError* error)) handler;
```
It should be 
```
-(void) listSocialLoginsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 completionHandler: (void (^)(DSUserSocialIdResult* output, NSError* error)) handler;

-(void) revokeOAuthTokenWithCompletionHandler: (void (^)(NSError* error)) handler;
```

**Comment by LarryKlugerDS** [comment]
Thank you for your comment. The SDK is auto-generated by the Swagger CodeGen tool. Unfortunately it does include some redundant data in the generated SDK.

Unfortunately, we don't plan to enhance the tool to correct this issue.
