### ISSUE TITLE
DSApiClient  configure_jwt_authorization_flow pem file issue

### ISSUE THREAD

**Issue by toseefkhilji** [docusign/docusign-objc-client#17]
Hi,

I am trying to authorization using jwt flow. 

 Code
```
 let docApi = DSApiClient(baseURL: URL(string: DSConstatns.host))
 docApi.configure_jwt_authorization_flow(DSConstatns.integrationKey, userId: DSConstatns.userId, oauthBasePath: DSConstatns.outhBasePath, privateKeyFilename: DSConstatns.privateKeyName, expiresIn: 3600)
```
But after calling `configure_jwt_authorization_flow` method, I'm getting pem file loading issue **`JWTCryptoSecurity error: Error Domain=NSCocoaErrorDomain Code=256 "The file couldn’t be opened."`**

I have valid pem file, tested my pem file with SdkTestsWithJwtAuth test class, and working fine.

![pem file](https://user-images.githubusercontent.com/2367614/42319637-3602ab28-8070-11e8-9135-91fb3ace8de8.png)

Please find code at below repo.
https://github.com/toseefkhilji/TestJWTSwift.git

Let me know what I'm missing with Pem file.

Thanks.

**Comment by LarryKlugerDS** [comment]
Will be covered as part of #21
