### ISSUE TITLE
No podspec found for `DocuSignESignClient` in `./sdk`

### ISSUE THREAD

**Issue by YGeorge** [docusign/docusign-objc-client#3]
I'm trying to install the library according to https://github.com/docusign/docusign-objc-client/blob/master/sdk/README.md

But I have an error:

> Create a file in your root project directory called podfile with the following content: 
> **pod "_DocuSignESignClient_", :path => "./sdk"**

Looks like README.md contains old incorrect instructions. Should I use 
**pod "_DocuSignESign_", :path => "./sdk"** instead?

**Comment by gsnavin** [comment]
@YGeorge You are correct, it needs to be 
pod "DocuSignESign", :path => "./sdk"

I will update the README.md along with the tests that go along with the SDK.
