### ISSUE TITLE
Lack of Documentation for iOS

### ISSUE THREAD

**Issue by drewpitchford** [docusign/docusign-objc-client#5]
Hi! I'm attempting to integrate docusign into a client app on iOS. The documentation for how to use this library is kind of limited in my opinion. Even the docs on the site are a bit confusing. We want a user to be able to sign within the app (without leaving it). So a couple of questions to begin with: Do we have to have the user provide some sort of authentication creds? Do we have to have native UI for the user to sign the PDF or is a webivew what is needed (UI is done by Docusign)? 

Really, a step by step guide on how to integrate this into an iOS app would be appreciated.

**Comment by dirtydanee** [comment]
+1

**Comment by dktan** [comment]
As I read through the code, I'm pretty sure that they don't have native UI for the user to sign the PDF. What they give is a url, just like their web api. And their code is buggy and docs are misleading.
So, this sdk kinda useless.

**Comment by mmallis87** [comment]
@drewpitchford @dirtydanee @dktan I think what you guys are looking for is the iOS native SDK: https://docs.docusign.com/ios_sdk/
That SDK has native UI for signing, is well documented and come with sample apps.

 That's been said, this pod lib is an http wrapper around DocuSign API. The API doesn't have a native way of signing. The API supports (in-app) browser signing only (web view, iframe...).

**Comment by dktan** [comment]
@mmallis87 This is what your website lead me to, and what docusign sales manager told me to look into. They have a lot to fix.

**Comment by mmallis87** [comment]
The native SDK is listed in the Developer Center under SDKs: https://www.docusign.com/developer-center/api-overview#sdks

We are aware that the documentation and the information architecture is misleading in the current Dev Center and we are fixing that in the new version that is going to be published in a month from now.

**Comment by suneelseelam** [comment]
Hi, I am using (https://github.com/docusign/docusign-ios-sdk) from past few years, currently I am getting an old SDK crash. so I thought to change the SDK But in the new SDK (https://github.com/docusign/docusign-objc-client) I have no Idea to integrate new SDK can anyone please share the example code if there to Integrate new SDK. Thanks in Advance.

**Comment by mmallis87** [comment]
@suneelseelam You'll find some examples here: https://github.com/docusign/docusign-objc-client/blob/master/test/SdkTests/SdkTestsTests/SdkTestsWithJwtAuth.m

**Comment by LarryKlugerDS** [comment]
A JWT .NET Core solution code example for the current version of the SDK is available here: https://github.com/docusign/blog-csharp-order-form 

In addition, other examples for C# are [available](https://github.com/docusign?utf8=%E2%9C%93&q=eg-01-cs&type=&language=) (see the repo list) but they are not yet updated to the new version of the SDK. That work is in progress and is expected to be complete by Nov 12, 2018
